before_script:

 - apt-get update -qq && apt-get install -y -qq sshpass

stages:

  - deploy

deploy_production:

  stage: deploy
  
  environment: Production
  
  only:
    - master
    
  script:
    - sshpass -V
    - export SSHPASS=$USER_PASS 
    - sshpass -e ssh qlicue@192.254.227.6
    - pwd
    - exit