before_script:
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H 'qlicue.co.tz' >> ~/.ssh/known_hosts
    
deploy_staging:
  type: deploy
  environment:
    name: production
  script:
    - ssh -p 2222 qlicue@192.254.227.6 "/home2/qlicue/public_html/uzzar && git checkout master && git pull origin master && exit"
  only:
    - master